#!/usr/bin/env python3
"""Ingest a real USDM v4.0 study definition into a cr-core project graph.

Reads a pinned, MIT-licensed DDF-RA example (the CDISC Pilot, LZZT) and maps its
design-time constructs onto TOP cr-core per crosswalks/usdm-to-cr.ttl — the
"protocol -> project KG" path, run for real on the canonical public example. Covers
the crosswalk-mapped design layer (study, protocol version, arms, eligibility,
endpoints, estimand, sponsor, and the Schedule of Activities: timeline + encounters
positioned by their USDM timings). Emits a conformant cr-domain graph. Deterministic.

Run:  python3 tools/usdm-rdf-gen/ingest_usdm.py
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "ddf-ra-v4.0.0", "examples", "CDISC_Pilot_Study.json")
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "examples", "usdm-cdisc-pilot-ingested.ttl"))
INGEST_DATE = "2026-06-23T00:00:00Z"   # transaction time of this ingestion (deterministic)


def slug(s):
    return re.sub(r"[^A-Za-z0-9]+", "-", str(s)).strip("-")


def iri(usdm_id):
    return "ex:cp-" + slug(usdm_id)


def esc(s):
    return str(s).replace("\\", "\\\\").replace('"', '\\"')


def iso_days(dur):
    """Crude ISO-8601 duration -> day magnitude (weeks/days; sub-day -> 0)."""
    if not dur:
        return None
    m = re.match(r"P(?:(\d+)W)?(?:(\d+)D)?", dur)
    if not m:
        return 0
    return (int(m.group(1) or 0) * 7) + int(m.group(2) or 0)


def main():
    d = json.load(open(SRC))
    study = d["study"]
    ver = study["versions"][0]
    sd = ver["studyDesigns"][0]
    src_id = study.get("id") or "CDISC-PILOT-LZZT"
    study_iri = iri(src_id)

    L = []
    w = L.append
    for p in ("ex|https://top.scientix.ai/examples/", "cr|https://top.scientix.ai/cr/v1#",
              "hcls|https://top.scientix.ai/hcls/v1#", "top|https://top.scientix.ai/core/v1#",
              "prov|http://www.w3.org/ns/prov#", "rdfs|http://www.w3.org/2000/01/rdf-schema#",
              "xsd|http://www.w3.org/2001/XMLSchema#"):
        pre, ns = p.split("|")
        w(f"@prefix {pre}: <{ns}> .")
    w("")
    w("# GENERATED by tools/usdm-rdf-gen/ingest_usdm.py from the real, MIT-licensed CDISC Pilot")
    w("# (LZZT) USDM v4.0 example (DDF-RA @ v4.0.0). The protocol's design landing in cr-core")
    w("# via crosswalks/usdm-to-cr.ttl. Do not hand-edit; re-run the ingester. Validates green.")
    w("")
    w('ex:cp-ingest a prov:Agent ; rdfs:label "USDM ingestion (DDF-RA CDISC Pilot, MIT)" .')
    src = f"<urn:usdm:{slug(src_id)}>"

    # --- Study (usdm:Study) ---
    arms = sd.get("arms", [])
    orgs = ver.get("organizations", [])
    site = next((o for o in orgs if "SITE" in (o.get("name") or "").upper()), None)
    sponsor = next((o for o in orgs
                    if "Sponsor" in ((o.get("type") or {}).get("decode") or "") and o is not site), None)
    site_iri = iri(site["id"]) if site else "ex:cp-site"
    w("")
    w("# --- Study identity, protocol version, sponsor, site ---")
    parts = [f'a cr:Study', f'rdfs:label "{esc(study.get("name",""))}"',
             f"prov:wasDerivedFrom {src}"]
    if sponsor:
        parts.append(f"cr:sponsoredBy {iri(sponsor['id'])}")
    parts.append(f"cr:conductedAt {site_iri}")
    if arms:
        parts.append("cr:hasArm " + ", ".join(iri(a["id"]) for a in arms))
    parts.append(f"cr:hasProtocolVersion {iri('pv-'+ver['id'])}")
    body = " ;\n    ".join(parts)
    w(f"{study_iri} {body} .")

    if sponsor:
        w(f'{iri(sponsor["id"])} a cr:Sponsor ; rdfs:label "{esc(sponsor.get("name",""))}" .')
    if site:
        w(f'{site_iri} a cr:StudySite ; rdfs:label "{esc(site.get("name",""))}" .')
    else:
        w(f'{site_iri} a cr:StudySite ; rdfs:label "Study site" .')

    elig = sd.get("eligibilityCriteria", [])
    pv = iri("pv-" + ver["id"])
    w(f"{pv} a cr:ProtocolVersion ; "
      f'rdfs:label "Protocol {esc(ver.get("versionIdentifier","1"))}" ;')
    if elig:
        w("    cr:hasEligibilityCriterion " + ", ".join(iri(c["id"]) for c in elig[:8]) + " ;")
    w(f'    prov:wasDerivedFrom {src} ;')
    w(f'    top:observedAt "2025-03-14T00:00:00Z"^^xsd:dateTime ;')
    w(f'    top:recordedAt "{INGEST_DATE}"^^xsd:dateTime ;')
    w(f'    top:identifier "urn:cdisc-pilot:pv" ; top:status "active" ;')
    w(f"    prov:wasAttributedTo ex:cp-ingest .")

    # --- Arms ---
    w("")
    w("# --- Arms (usdm:StudyArm) ---")
    for a in arms:
        w(f'{iri(a["id"])} a cr:Arm ; rdfs:label "{esc(a.get("name",""))}" .')

    # --- Eligibility (usdm:EligibilityCriterion) ---
    w("")
    w("# --- Eligibility criteria (usdm:EligibilityCriterion) ---")
    for c in elig:
        cat = (c.get("category") or {}).get("decode", "")
        lbl = c.get("label") or c.get("name") or c.get("identifier") or c["id"]
        suffix = f" ({esc(cat)})" if cat else ""
        w(f'{iri(c["id"])} a cr:EligibilityCriterion ; rdfs:label "{esc(lbl)}{suffix}" .')

    # --- Objectives -> Endpoints (usdm:Endpoint) + Estimand ---
    w("")
    w("# --- Endpoints (usdm:Endpoint) + estimand (usdm:Estimand) ---")
    for ob in sd.get("objectives", []):
        for ep in ob.get("endpoints", []):
            lbl = ep.get("label") or ep.get("name") or (ep.get("text", "")[:60]) or ep["id"]
            w(f'{iri(ep["id"])} a cr:Endpoint ; rdfs:label "{esc(lbl)}" .')
    for es in sd.get("estimands", []):
        lbl = es.get("label") or es.get("name") or es["id"]
        w(f'{iri(es["id"])} a cr:Estimand ; rdfs:label "{esc(lbl)}" .')

    # --- Schedule of Activities (usdm:ScheduleTimeline / Encounter / Timing) ---
    tl = next((t for t in sd.get("scheduleTimelines", []) if t.get("mainTimeline")),
              (sd.get("scheduleTimelines") or [None])[0])
    encounters = sd.get("encounters", [])
    w("")
    w("# --- Schedule of Activities: timeline + encounters positioned by USDM timings ---")
    if tl and encounters:
        sai_enc = {i["id"]: i.get("encounterId") for i in tl.get("instances", []) if i.get("encounterId")}
        # encounter -> the timing that positions it (its from-instance maps to it)
        enc_timing = {}
        for t in tl.get("timings", []):
            enc = sai_enc.get(t.get("relativeFromScheduledInstanceId"))
            if enc and enc not in enc_timing:
                enc_timing[enc] = t
        tliri = iri("tl-" + tl["id"])
        w(f'{tliri} a cr:ScheduleTimeline ; rdfs:label "{esc(tl.get("label") or tl.get("name") or "SoA")}" ;')
        w("    cr:hasPlannedEncounter " + ", ".join(iri(e["id"]) for e in encounters) + " ;")
        w(f"    prov:wasDerivedFrom {src} ;")
        w(f'    top:observedAt "2025-03-14T00:00:00Z"^^xsd:dateTime ;')
        w(f'    top:recordedAt "{INGEST_DATE}"^^xsd:dateTime ;')
        w('    top:identifier "urn:cdisc-pilot:soa" ; top:status "active" ;')
        w("    prov:wasAttributedTo ex:cp-ingest .")
        for e in encounters:
            t = enc_timing.get(e["id"])
            tg = iri("t-" + e["id"])
            w(f'{iri(e["id"])} a cr:PlannedEncounter ; rdfs:label "{esc(e.get("label") or e.get("name") or e["id"])}" ; cr:timing {tg} .')
            if t:
                dec = (t.get("type") or {}).get("decode", "") or ""
                tt = "before" if "Before" in dec else ("after" if "After" in dec else "fixed")
                days = iso_days(t.get("value"))
                anchor = sai_enc.get(t.get("relativeToScheduledInstanceId"))
                tparts = [f'cr:timingType "{tt}"']
                if days is not None:
                    tparts.append(f"cr:offsetDays {days}")
                if anchor and anchor != e["id"]:
                    tparts.append(f"cr:relativeTo {iri(anchor)}")
                wl, wu = iso_days(t.get("windowLower")), iso_days(t.get("windowUpper"))
                if wl is not None or wu is not None:
                    wiri = iri("w-" + e["id"])
                    tparts.append(f"cr:window {wiri}")
                    w(f"{wiri} a cr:Window ; cr:windowLowerDays {-(wl or 0)} ; cr:windowUpperDays {wu or 0} .")
                w(f'{tg} a cr:Timing ; {" ; ".join(tparts)} .')
            else:
                w(f'{tg} a cr:Timing ; cr:timingType "fixed" ; cr:offsetDays 0 ; cr:relativeTo {tliri} .')

    out = "\n".join(L) + "\n"
    with open(OUT, "w") as f:
        f.write(out)
    n = out.count(" a cr:") + out.count(" a hcls:")
    print(f"wrote {OUT}: ~{n} entities from {study.get('name')} ({len(encounters)} encounters, "
          f"{len(arms)} arms, {len(elig)} eligibility)")


if __name__ == "__main__":
    main()
