#!/usr/bin/env python3
"""Ingest a real USDM v4.0 study definition into a cr-core project graph.

Reads a pinned, MIT-licensed DDF-RA example (the CDISC Pilot, LZZT) and maps its
design-time constructs onto TOP cr-core per crosswalks/usdm-to-cr.ttl — the
"protocol -> project KG" path, run for real on the canonical public example. Covers
the crosswalk-mapped design layer (study, protocol version, arms, eligibility,
endpoints, estimand, sponsor, and the Schedule of Activities: timeline + encounters
positioned by their USDM timings). Emits a conformant cr-domain graph. Deterministic.

Universal DNA (issue #48): every emitted CommonEntity node is stamped at ingestion
with the three strands Core requires — top:identifier (a stable URN minted from the
source entity id), top:observedAt (the ingestion timestamp: the honest world-entry
time of the ingested assertion), top:status ("active"). All other values come from
the source document, never invented.

Run:  python3 tools/usdm-rdf-gen/ingest_usdm.py
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "ddf-ra-v4.0.0", "examples", "CDISC_Pilot_Study.json")
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "examples", "usdm-cdisc-pilot-ingested.ttl"))
INGEST_DATE = "2026-06-23T00:00:00Z"     # transaction time of this ingestion (deterministic)
PROTOCOL_DATE = "2025-03-14T00:00:00Z"   # DDF-RA v4.0.0 source snapshot (protocol observation)


def slug(s):
    return re.sub(r"[^A-Za-z0-9]+", "-", str(s)).strip("-")


def iri(usdm_id):
    return "ex:cp-" + slug(usdm_id)


def esc(s):
    return str(s).replace("\\", "\\\\").replace('"', '\\"')


def dna(local):
    """The three Universal DNA strands, stamped at ingestion time (issue #48).

    identifier: stable URN minted from the source entity id (same local name as the
    IRI, so re-runs never remint). observedAt: the ingestion timestamp — the honest
    world-entry time of the ingested assertion. status: "active"."""
    return (f'top:identifier "urn:cdisc-pilot:{local}"^^xsd:anyURI ; '
            f'top:observedAt "{INGEST_DATE}"^^xsd:dateTime ; top:status "active"')


def iso_days(dur):
    """Crude ISO-8601 duration -> day magnitude (weeks/days; sub-day -> 0)."""
    if not dur:
        return None
    m = re.match(r"P(?:(\d+)W)?(?:(\d+)D)?", dur)
    if not m:
        return 0
    return (int(m.group(1) or 0) * 7) + int(m.group(2) or 0)


def main():
    d = json.load(open(SRC, encoding="utf-8"))
    study = d["study"]
    ver = study["versions"][0]
    sd = ver["studyDesigns"][0]
    src_id = study.get("id") or "CDISC-PILOT-LZZT"
    study_iri = iri(src_id)

    L = []
    w = L.append
    for p in ("ex|https://top.scientix.ai/examples/", "cr|https://top.scientix.ai/cr/v1#",
              "hcls|https://top.scientix.ai/hcls/v1#", "top|https://top.scientix.ai/v1#",
              "prov|http://www.w3.org/ns/prov#", "rdfs|http://www.w3.org/2000/01/rdf-schema#",
              "xsd|http://www.w3.org/2001/XMLSchema#"):
        pre, ns = p.split("|")
        w(f"@prefix {pre}: <{ns}> .")
    w("")
    w("# GENERATED by tools/usdm-rdf-gen/ingest_usdm.py from the real, MIT-licensed CDISC Pilot")
    w("# (LZZT) USDM v4.0 example (DDF-RA @ v4.0.0). The protocol's design landing in cr-core")
    w("# via crosswalks/usdm-to-cr.ttl. Do not hand-edit; re-run the ingester. Validates green.")
    w("# Universal DNA (identifier/observedAt/status) is stamped at ingestion time (issue #48).")
    w("")
    w('ex:cp-ingest a prov:Agent ; rdfs:label "USDM ingestion (DDF-RA CDISC Pilot, MIT)" .')
    src = f"<urn:usdm:{slug(src_id)}>"

    # --- Study (usdm:Study) ---
    arms = sd.get("arms", [])
    orgs = ver.get("organizations", [])
    site = next((o for o in orgs if "SITE" in (o.get("name") or "").upper()), None)
    sponsor = next((o for o in orgs
                    if "Sponsor" in ((o.get("type") or {}).get("decode") or "") and o is not site), None)
    site_iri = iri(site["id"]) if site else "ex:cp-site"
    phase = ((sd.get("studyPhase") or {}).get("standardCode") or {}).get("decode")
    ta = next((t.get("decode") for t in sd.get("therapeuticAreas", []) if t.get("decode")), None)
    proto_label = f'Protocol {esc(ver.get("versionIdentifier", "1"))}'
    w("")
    w("# --- Study identity, protocol version, sponsor, site ---")
    parts = [f'a cr:Study', f'rdfs:label "{esc(study.get("name",""))}"',
             f"prov:wasDerivedFrom {src}"]
    if sponsor:
        parts.append(f"cr:sponsoredBy {iri(sponsor['id'])}")
    parts.append(f"cr:conductedAt {site_iri}")
    if arms:
        parts.append("cr:hasArm " + ", ".join(iri(a["id"]) for a in arms))
    parts.append(f"cr:hasProtocolVersion {iri('pv-'+ver['id'])}")
    if sponsor:
        parts.append(f'cr:sponsorName "{esc(sponsor.get("label") or sponsor.get("name", ""))}"')
    if phase:
        parts.append(f'cr:studyPhase "{esc(phase)}"')
    if ta:
        parts.append(f'cr:therapeuticArea "{esc(ta)}"')
    parts.append(f'cr:protocolVersion "{proto_label}"')
    parts.append(dna(slug(src_id)))
    body = " ;\n    ".join(parts)
    w(f"{study_iri} {body} .")

    if sponsor:
        w(f'{iri(sponsor["id"])} a cr:Sponsor ; rdfs:label "{esc(sponsor.get("name",""))}" ;')
        w(f'    {dna(slug(sponsor["id"]))} .')
    if site:
        w(f'{site_iri} a cr:StudySite ; rdfs:label "{esc(site.get("name",""))}" ;')
        w(f'    {dna(slug(site["id"]))} .')
    else:
        w(f'{site_iri} a cr:StudySite ; rdfs:label "Study site" ;')
        w(f'    {dna("site")} .')

    elig = sd.get("eligibilityCriteria", [])
    pv = iri("pv-" + ver["id"])
    # cr:ProtocolVersion is top:Versioned (KEEP, VERSIONED_LEDGER.md): beyond DNA it
    # carries the full bitemporal envelope — validFrom + prov:specializationOf -> a
    # stable top:VersionSeries. validFrom comes from the source's approval date.
    approval = next((dv.get("dateValue") for dv in ver.get("dateValues", [])
                     if "Approval" in ((dv.get("type") or {}).get("decode") or "")), None)
    valid_from = f"{approval}T00:00:00Z" if approval else PROTOCOL_DATE
    pv_series = pv + "-series"
    w(f'{pv_series} a top:VersionSeries ; rdfs:label "VersionSeries for {proto_label}" .')
    w(f"{pv} a cr:ProtocolVersion ; "
      f'rdfs:label "{proto_label}" ;')
    if elig:
        w("    cr:hasEligibilityCriterion " + ", ".join(iri(c["id"]) for c in elig[:8]) + " ;")
    w(f'    prov:wasDerivedFrom {src} ;')
    w(f'    top:observedAt "{PROTOCOL_DATE}"^^xsd:dateTime ;')
    w(f'    top:recordedAt "{INGEST_DATE}"^^xsd:dateTime ;')
    w(f'    top:identifier "urn:cdisc-pilot:pv"^^xsd:anyURI ; top:status "active" ;')
    w(f'    top:validFrom "{valid_from}"^^xsd:dateTime ;')
    w(f'    prov:specializationOf {pv_series} ;')
    w(f"    prov:wasAttributedTo ex:cp-ingest .")

    # --- Arms ---
    w("")
    w("# --- Arms (usdm:StudyArm) ---")
    for a in arms:
        w(f'{iri(a["id"])} a cr:Arm ; rdfs:label "{esc(a.get("name",""))}" ;')
        w(f'    {dna(slug(a["id"]))} .')

    # --- Eligibility (usdm:EligibilityCriterion) ---
    w("")
    w("# --- Eligibility criteria (usdm:EligibilityCriterion) ---")
    for c in elig:
        cat = (c.get("category") or {}).get("decode", "")
        lbl = c.get("label") or c.get("name") or c.get("identifier") or c["id"]
        suffix = f" ({esc(cat)})" if cat else ""
        ctype = "exclusion" if cat.lower().startswith("excl") else "inclusion"
        w(f'{iri(c["id"])} a cr:EligibilityCriterion ; rdfs:label "{esc(lbl)}{suffix}" ;')
        w(f'    cr:criterionText "{esc(lbl)}{suffix}" ;')
        w(f'    cr:criterionType "{ctype}" ;')
        w(f'    {dna(slug(c["id"]))} .')

    # --- Objectives -> Endpoints (usdm:Endpoint) + Estimand ---
    w("")
    w("# --- Endpoints (usdm:Endpoint) + estimand (usdm:Estimand) ---")
    ep_by_id = {}
    for ob in sd.get("objectives", []):
        for ep in ob.get("endpoints", []):
            ep_by_id[ep["id"]] = ep
            lbl = ep.get("label") or ep.get("name") or (ep.get("text", "")[:60]) or ep["id"]
            w(f'{iri(ep["id"])} a cr:Endpoint ; rdfs:label "{esc(lbl)}" ;')
            w(f'    {dna(slug(ep["id"]))} .')
    ap_by_id = {ap["id"]: ap for ap in sd.get("analysisPopulations", [])}
    for es in sd.get("estimands", []):
        lbl = es.get("label") or es.get("name") or es["id"]
        w(f'{iri(es["id"])} a cr:Estimand ;')
        w(f'    rdfs:label "{esc(lbl)}" ;')
        ap = ap_by_id.get(es.get("analysisPopulationId")) or {}
        ap_text = ap.get("text") or ap.get("label") or ap.get("name")
        if ap_text:
            w(f'    cr:estimandPopulation "{esc(ap_text)}" ;')
        voi = ep_by_id.get(es.get("variableOfInterestId")) or {}
        voi_text = voi.get("text") or voi.get("label") or voi.get("name")
        if voi_text:
            w(f'    cr:estimandVariable "{esc(voi_text)}" ;')
        strategy = next((ie.get("strategy") for ie in es.get("intercurrentEvents", [])
                         if ie.get("strategy")), None)
        if strategy:
            w(f'    cr:intercurrentEventStrategy "{esc(strategy)}" ;')
        if es.get("populationSummary"):
            w(f'    cr:populationLevelSummary "{esc(es["populationSummary"])}" ;')
        w(f'    {dna(slug(es["id"]))} .')

    # --- Schedule of Activities (usdm:ScheduleTimeline / Encounter / Timing) ---
    tl = next((t for t in sd.get("scheduleTimelines", []) if t.get("mainTimeline")),
              (sd.get("scheduleTimelines") or [None])[0])
    encounters = sd.get("encounters", [])
    w("")
    w("# --- Schedule of Activities: timeline + encounters positioned by USDM timings ---")
    if tl and encounters:
        sai_enc = {i["id"]: i.get("encounterId") for i in tl.get("instances", []) if i.get("encounterId")}
        # encounter -> the timing that positions it (its from-instance maps to it)
        enc_timing = {}
        for t in tl.get("timings", []):
            enc = sai_enc.get(t.get("relativeFromScheduledInstanceId"))
            if enc and enc not in enc_timing:
                enc_timing[enc] = t
        tliri = iri("tl-" + tl["id"])
        w(f'{tliri} a cr:ScheduleTimeline ; rdfs:label "{esc(tl.get("label") or tl.get("name") or "SoA")}" ;')
        w("    cr:hasPlannedEncounter " + ", ".join(iri(e["id"]) for e in encounters) + " ;")
        w(f"    prov:wasDerivedFrom {src} ;")
        w(f'    top:observedAt "{PROTOCOL_DATE}"^^xsd:dateTime ;')
        w(f'    top:recordedAt "{INGEST_DATE}"^^xsd:dateTime ;')
        w('    top:identifier "urn:cdisc-pilot:soa"^^xsd:anyURI ; top:status "active" ;')
        w("    prov:wasAttributedTo ex:cp-ingest .")
        for e in encounters:
            t = enc_timing.get(e["id"])
            tg = iri("t-" + e["id"])
            w(f'{iri(e["id"])} a cr:PlannedEncounter ; rdfs:label "{esc(e.get("label") or e.get("name") or e["id"])}" ; cr:timing {tg} ;')
            w(f'    {dna(slug(e["id"]))} .')
            if t:
                dec = (t.get("type") or {}).get("decode", "") or ""
                tt = "before" if "Before" in dec else ("after" if "After" in dec else "fixed")
                days = iso_days(t.get("value"))
                anchor = sai_enc.get(t.get("relativeToScheduledInstanceId"))
                tparts = [f'cr:timingType "{tt}"']
                if days is not None:
                    tparts.append(f"cr:offsetDays {days}")
                if anchor and anchor != e["id"]:
                    tparts.append(f"cr:relativeTo {iri(anchor)}")
                wl, wu = iso_days(t.get("windowLower")), iso_days(t.get("windowUpper"))
                if wl is not None or wu is not None:
                    wiri = iri("w-" + e["id"])
                    tparts.append(f"cr:window {wiri}")
                    w(f"{wiri} a cr:TimingWindow ; cr:windowLowerDays {-(wl or 0)} ; cr:windowUpperDays {wu or 0} ;")
                    w(f'    {dna(slug("w-" + e["id"]))} .')
                w(f'{tg} a cr:Timing ; {" ; ".join(tparts)} ;')
                w(f'    {dna(slug("t-" + e["id"]))} .')
            else:
                w(f'{tg} a cr:Timing ; cr:timingType "fixed" ; cr:offsetDays 0 ; cr:relativeTo {tliri} ;')
                w(f'    {dna(slug("t-" + e["id"]))} .')

    w("")
    w("# Provenance identity — attribution targets are identified agents, not bare roles.")
    w('ex:cp-ingest top:identifier "system:usdm-ingest-ddf-ra"^^xsd:anyURI ;')
    w(f'    top:observedAt "{INGEST_DATE}"^^xsd:dateTime ; top:status "active" .')

    out = "\n".join(L) + "\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(out)
    n = out.count(" a cr:") + out.count(" a hcls:")
    print(f"wrote {OUT}: ~{n} entities from {study.get('name')} ({len(encounters)} encounters, "
          f"{len(arms)} arms, {len(elig)} eligibility)")


if __name__ == "__main__":
    main()
